### PR TITLE
Removed named-regexp dependency and java version 1.6 to 1.7

### PR DESCRIPTION
**Pull request by hayatbehlim**
@anthonycorbacho  Its possible to merge my commit to remove dependency of named-regex lib

### CODE REVIEW

**Comment by hayatbehlim** [comment]
@anthonycorbacho Its possible to merge this pull request and release new  version ,Hope this will improve CPU performance.

**Comment by trixpan** [comment]
:+1: on this.

**Comment by trixpan** [comment]
@anthonycorbacho any chances of merging this?

**Comment by anthonycorbacho** [comment]
Sorry i totally forgot about this PR..

looks great thank you for the contrib.

**Comment by trixpan** [comment]
would it be worth push this into Maven Central as version 0.2.0 by any chance (assuming some semantic versioning due to the major change from JRE6 to JRE7 and above)?

**Comment by trixpan** [comment]
(thanks for the merge by the way)

**Pull request merged**
