### PR TITLE
Allow classpath pattern files

### PR DESCRIPTION
**Pull request by paulwellnerbou**
Refactoring, simplifying code, improving exception handling and, most important, ship included patterns as resources and use them as default when creating the Grok object.

### CODE REVIEW

**Comment by paulwellnerbou** [comment]
@anthonycorbacho, is there any chance to get this in? And release a new version?
If not, I would fork it and release the work publicly.

**Comment by fbacchella** [comment]
@anthonycorbacho any hope for any merge ?

**Comment by paulwellnerbou** [comment]
@fbacchella, as there does not seem to happen anything here, I released my own branch as 0.1.6: https://bintray.com/paulwellnerbou/maven/java-grok

**Comment by fbacchella** [comment]
What is needed is a semi-official fork, hosted on maven central. And perhaps you could contact @keitaf who seems to have intersting performance patches.

**Comment by paulwellnerbou** [comment]
@fbacchella, I requested it to be included into the official jcenter repositories. In the meantime you can add the repository manually in your build files. For Gradle, add:

```
repositories {
    maven {
        url  "https://dl.bintray.com/paulwellnerbou/maven" 
    }
}
```

I suggest using https://github.com/paulwellnerbou/java-grok as "semi official fork" until @anthonycorbacho appears again.

Is @keitaf able to create pull requests against my master branch? I have no problem in integrating them and creating a new release on bintray.

**Comment by keitaf** [comment]
@paulwellnerbou here is the PR.
https://github.com/paulwellnerbou/java-grok/pull/1

I also made API changes that are not backward compatible. Please feel free to test it and merge it to your fork if you like the new API.

**Comment by anthonycorbacho** [comment]
Sorry for the late answer.

Looks good to me.

**Comment by paulwellnerbou** [comment]
@anthonycorbacho, we have some more pull requests now in another fork, see https://github.com/paulwellnerbou/java-grok.

**Comment by ottobackwards** [comment]
I've been talking to Anthony about keeping this project going, including a mailing list or something where we can communicate better, and possibly having more committers and reviewers.  It would be great if we could consolidate the PR's back to here and give it a shot.

**Comment by anthonycorbacho** [comment]
Yeah i am fine, pong me when its ready.

I will also take care of some refacto but ibthink ibwill wait until the port is done

**Comment by ottobackwards** [comment]
@anthonycorbacho, when you feel like you are done with the prs and possibly ready for 1.6.0 we need to know, then if @paulwellnerbou can do the pull, I can look at doing the PR to re-integrate, unless you want to.

You have my email, please feel free to email for help.

**Comment by paulwellnerbou** [comment]
Yes, a new major makes sense. The major breaking changes were just merged by @anthonycorbacho to master. The performance improvements and refactorings by @keitaf changed the API again a bit. So yes, we have breaking changes. And we discard java 7 now.

**Comment by ottobackwards** [comment]
Ok, so if I understand correctly, the PR's in your branch with the breaking changes have been merged into *this* repo just now, and the rest of your changes are not breaking?
So there may be some consideration for skipping 1.6 then?

**Comment by ottobackwards** [comment]
If that is the case, then maybe when @anthonycorbacho is done his current set of work and pr merges I can do the pr from your fork and *then* 2.0 would make more sense?

**Comment by anthonycorbacho** [comment]
Okay, so before releasing, i want to remove maven and clean up a little bit.

@paulwellnerbou is there any change that need to be added to this repo?

**Comment by ottobackwards** [comment]
don't forget to reference and close https://github.com/thekrakken/java-grok/issues/32 when you nuke maven

**Comment by paulwellnerbou** [comment]
@ottobackwards, @anthonycorbacho, maven is removed already in our fork.

Regarding the breaking changes: @ottobackwards, yes, that's partly correct. The breaking changes were just merged into *this* repository by @anthonycorbacho accepting my PR. Although @keitaf's refactoring and performance improvements will bring some more breaking changes (see https://github.com/paulwellnerbou/java-grok/pull/1).

I will create a PR right now. You will have to restore the CI configuration though, I removed it, too.

**Pull request merged**
