### PR TITLE
Fixed  Index Out Of Bounds Exception

### PR DESCRIPTION
**Pull request by hayatbehlim**
Return empty string when input string contain only one special char  like ( " , ' etc)

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
@hayatbehlim , thank you for your contribution 👍

**Comment by hayatbehlim** [comment]
@anthonycorbacho You are welcome :+1:   I am  facing Index Out Bound exception in my application. If you don't mind can I know, When you are planning to release next version of this So I can find this fix in it?

**Comment by anthonycorbacho** [comment]
@hayatbehlim just did

**Comment by hayatbehlim** [comment]
Thanks :+1:

**Pull request merged**
