### PR TITLE
Preserve the order of log format in capture

### PR DESCRIPTION
**Pull request by SivaMaplelabs**
Dear java-grok maintainers,

Please accept this PR.

**Analysis**
Currently, capture is returning the unordered Map.

**Resolution**
Return the map with the same order as log format(pattern).

**Test**
Tested with different types of logs.

### CODE REVIEW

**Comment by SivaMaplelabs** [comment]
@anthonycorbacho @paulwellnerbou @ottobackwards Please review and merge this PR.

**Comment by SivaMaplelabs** [comment]
@ottobackwards Thank you so much for the review. This is the most urgent and important fix for our project.
1. Need others views too.
2. Agree with you, it's not mandatory to change to LinkedHashMap. Will remove the changes in the documentation. 
 3. Sure, will add the unit tests in the PR.

**Comment by ottobackwards** [comment]
Thanks @SivaMaplelabs, could you change the tests or add new tests the specifically test that the map iteration matches the capture order?  That is the point.

**Comment by SivaMaplelabs** [comment]
@ottobackwards 
Following lines test the "preserve order". 
https://github.com/thekrakken/java-grok/pull/106/files#diff-706258725dfb91a78f94974320bde826R57
https://github.com/thekrakken/java-grok/pull/106/files#diff-706258725dfb91a78f94974320bde826R72
Thanks

**Comment by paulwellnerbou** [comment]
@SivaMaplelabs , looks great. Unfortunately I don't have rights to publish it, I would have to create an own version again, as I did with https://github.com/paulwellnerbou/java-grok/releases/tag/0.1.8 and https://bintray.com/paulwellnerbou/maven/java-grok/0.1.8

**Comment by SivaMaplelabs** [comment]
@anthonycorbacho Could you please review and merge this PR?

**Comment by anthonycorbacho** [comment]
Hi,

Sure i will do it after landing, it will be in couple of hours.

**Comment by SivaMaplelabs** [comment]
Sure.  Thanks.

**Comment by anthonycorbacho** [comment]
Reviewed and merged, thanks for your contribution 💃

**Comment by SivaMaplelabs** [comment]
@anthonycorbacho Thanks

**Pull request merged**
