### PR TITLE
GrokCompiler.compile don't document unchecked exception.

### PR DESCRIPTION
**Pull request by fbacchella**
GrokCompiler.compile should document exception it throws, even unchecked one. I think it helps tools like Eclipse to auto-generate code.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Since this is a runtime exception, adding the `throws` does not require a change to callers who may not have been catching, so +1 from me.

**Comment by fbacchella** [comment]
I don't think the style failure are mine.

**Comment by fbacchella** [comment]
Done.

**Comment by anthonycorbacho** [comment]
Arf, it bring conflict again by merging the other pr :(

**Comment by fbacchella** [comment]
Done.

**Pull request merged**
