### PR TITLE
Deep recursion postfix patterns

### LINKED ISSUE #66: Valid patterns failing with "Deep recursion pattern"
The valid grok patterns for parsing Postfix logs available at https://github.com/whyscream/postfix-grok-patterns/blob/f0ec34dcc6250463a30ba2077d8afa89ee1a17a1/postfix.grok fail to work with this grok library if the "only named captures" option is being used.

Logstash seems to have no problems with these patterns.

Exception (for the pattern `%{POSTFIX_SMTPD}`):
```text
io.thekraken.grok.api.exception.GrokException: Deep recursion pattern compilation of %{POSTFIX_SMTPD}
	at io.thekraken.grok.api.Grok.compile(Grok.java:355)
```

### PR DESCRIPTION
**Pull request by retoo**
Incorporates the tests from https://github.com/thekrakken/java-grok/pull/67 and fixes https://github.com/thekrakken/java-grok/issues/66

Grok/compile aborts now if a definition cannot be resolved. 

@anthonycorbacho I have no idea often this might break actual setups. The unit tests are green ;)

### CODE REVIEW

**Comment by retoo** [comment]
Also completes the PR https://github.com/thekrakken/java-grok/pull/29, solves the same problem.

**Comment by retoo** [comment]
@anthonycorbacho I already resolved the conflict this PR, please merge the Pull Request https://github.com/thekrakken/java-grok/pull/70 first, afterwards you can merge this one (which then should have no conflict).

**Comment by anthonycorbacho** [comment]
@retoo I merged #70 

Once you resolve the conflict here, i will merge this pr as well :)

**Comment by retoo** [comment]
@anthonycorbacho  strange; no idea why it didn't work. Anyway, now it's rebased.

**Comment by joschi** [comment]
@anthonycorbacho Would it be possible to get a release of java-grok with this fix?

**Comment by retoo** [comment]
@anthonycorbacho yes please!

@joschi you can use the jetpack.io distribution if you like:
 => https://jitpack.io/#thekrakken/java-grok/551fadba59

**Pull request merged**
