### PR TITLE
add option to keep empty captures

### PR DESCRIPTION
**Pull request by ottobackwards**
Per: https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html#plugins-filters-grok-keep_empty_captures

---
This change is [Reviewable](https://reviewable.io/reviews/thekrakken/java-grok/79)

### CODE REVIEW

**Comment by ramondg** [comment]
+1

**Comment by fbacchella** [comment]
This repo is almost dead, no one will merge it. See https://github.com/thekrakken/java-grok/pull/73 for more discussions about that.

**Comment by anthonycorbacho** [comment]
Hi,

Sorry for the silence, i am ultra busy at work

Can you fix the unit test.
Lets merge it asap.

**Comment by ottobackwards** [comment]
I've tracked the changes from this morning, and updated to use the check style and intellij styles.  I also started building with gradle as opposed to mvn, to get the checkstyle to run locally

**Comment by anthonycorbacho** [comment]
@ottobackwards i am sorry, i bring conflict, can you rebase and ping me back so i can merge it

**Comment by ottobackwards** [comment]
Done.

**Comment by ottobackwards** [comment]
Does this need to be re-submitted?

**Comment by anthonycorbacho** [comment]
The logic changed a little bit between the merge back. If you have time can
you take a look? I can also help let me know

**Pull request merged**
