### PR TITLE
Add option to capture named expressions only.

### PR DESCRIPTION
**Pull request by lwf**
Adds a boolean option to compile to only include named expressions.

### CODE REVIEW

**Comment by anthonycorbacho** [comment]
Code look great,
Thank you~

**Comment by jrask** [comment]
Great! 
Will there be a release with these features coming soon? I saw that the latest release was from 2014?

**Comment by anthonycorbacho** [comment]
@jrask I just released a new version `1.3.0`

**Comment by jrask** [comment]
@anthonycorbacho - Awesome!

**Pull request merged**
